package com.segfault03.ideadb;

import com.segfault03.ideadb.model.*;
import com.segfault03.ideadb.service.DataService;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

/** An owned in-memory database verifies explicit identities and edits using the original key. */
class AutoColumnMutationTest {
    @Test void explicitAndGeneratedIdentitiesCanBeInsertedAndExistingIdentitiesUpdated() throws Exception {
        ConnectionConfig config = new ConnectionConfig(DatabaseType.HSQLDB, "Auto edit test");
        String url = "jdbc:hsqldb:mem:auto_edit_" + UUID.randomUUID().toString().replace("-", "");
        Properties credentials = new Properties();
        credentials.setProperty("user", "SA");
        credentials.setProperty("password", "");
        // Avoid DriverManager service-loading unrelated drivers and their cleanup threads.
        try (var connection = new org.hsqldb.jdbc.JDBCDriver().connect(url, credentials); var sql = connection.createStatement()) {
            try {
                sql.execute("CREATE TABLE PUBLIC.AUTO_ROWS (ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR(40))");
                DataService service = DataService.getInstance();
                service.commitChanges(connection, config, "PUBLIC", "AUTO_ROWS",
                        List.of(Map.of("NAME", "Generated"), Map.of("ID", 42, "NAME", "Explicit")), List.of());
                int generated;
                try (var result = sql.executeQuery("SELECT ID FROM PUBLIC.AUTO_ROWS WHERE NAME='Generated'")) {
                    assertTrue(result.next()); generated = result.getInt(1);
                }
                var originalKeys = RowIdentity.originalKeys(List.of("ID", "NAME"),
                        List.of(generated, "Generated"), List.of("ID"));
                service.commitChanges(connection, config, "PUBLIC", "AUTO_ROWS", List.of(),
                        List.of(new DataService.RowUpdate(Map.of("ID", 100, "NAME", "Edited"), originalKeys)));
                try (var result = sql.executeQuery("SELECT ID, NAME FROM PUBLIC.AUTO_ROWS ORDER BY ID")) {
                    assertTrue(result.next()); assertEquals(42, result.getInt(1)); assertEquals("Explicit", result.getString(2));
                    assertTrue(result.next()); assertEquals(100, result.getInt(1)); assertEquals("Edited", result.getString(2));
                    assertFalse(result.next());
                }
            } finally { sql.execute("SHUTDOWN"); }
        }
    }
}
