name: Feature request
description: Suggest an improvement to database workflows
title: '[Feature] '
body:
  - type: textarea
    id: problem
    attributes:
      label: Task and current obstacle
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior and alternatives
    validations:
      required: true
